/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dfd7e3',
        'secondary-container': '#c7dfff',
        'brand-pink': '#e16b99',
        'link-blue': '#006bff',
        'on-surface-variant': '#4a4453',
        'primary-fixed': '#ebddff',
        'secondary-fixed': '#d1e4ff',
        outline: '#7b7484',
        'secondary-fixed-dim': '#b1c8e8',
        'brand-navy': '#001b33',
        'brand-navy-deep': '#001426',
        'inverse-surface': '#322f37',
        'on-background': '#1d1a22',
        'on-secondary-fixed': '#011d35',
        charcoal: '#37352f',
        'brand-orange': '#d9730d',
        'tint-mint': '#eaf6f0',
        'tertiary-fixed-dim': '#ffb866',
        'brand-teal': '#337ea9',
        secondary: '#49607b',
        surface: '#f7f7f5',
        'on-secondary': '#ffffff',
        tertiary: '#663d00',
        'tint-rose': '#ffebf1',
        'primary-fixed-dim': '#d3bbff',
        'tertiary-fixed': '#ffddba',
        slate: '#5a5a5a',
        'on-error': '#ffffff',
        'outline-variant': '#ccc3d5',
        hairline: '#e9e9e7',
        'on-primary-fixed-variant': '#5726a8',
        'on-primary': '#ffffff',
        'primary-container': '#6f42c1',
        canvas: '#ffffff',
        'surface-container-lowest': '#ffffff',
        ink: '#121212',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#673d00',
        'hairline-strong': '#d1d1cf',
        primary: '#5625a8',
        'surface-container-highest': '#e7e0eb',
        'tint-peach': '#fff0e8',
        'surface-container-high': '#ede6f1',
        'on-surface': '#1d1a22',
        'tint-yellow-bold': '#ffd54f',
        'tint-lavender': '#f3efff',
        'ink-deep': '#000000',
        'on-secondary-container': '#4c637e',
        'on-primary-fixed': '#250059',
        'inverse-on-surface': '#f6eefa',
        'surface-container': '#f3ebf7',
        'on-primary-container': '#e2d0ff',
        'surface-tint': '#7043c2',
        'on-tertiary': '#ffffff',
        stone: '#adafb0',
        'brand-navy-mid': '#0e2a47',
        'surface-variant': '#e7e0eb',
        steel: '#979a9b',
        'on-secondary-fixed-variant': '#314862',
        'tertiary-container': '#875200',
        background: '#fef7ff',
        'on-error-container': '#93000a',
        'surface-bright': '#fef7ff',
        'tint-yellow': '#fff9e6',
        'on-tertiary-fixed': '#2b1700',
        'error-container': '#ffdad6',
        'surface-container-low': '#f9f1fc',
        'inverse-primary': '#d3bbff',
        'tint-sky': '#e7f3ff',
        'surface-soft': '#fbfaf9',
        'on-tertiary-container': '#ffd09e',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '64px',
        hero: '120px',
        'section-lg': '96px',
        base: '16px',
      },
      borderRadius: {
        DEFAULT: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      opacity: {
        45: '0.45',
      },
    },
  },
  plugins: [],
}
